version: '3'

services:
  app:
    build: .
    hostname: "app"
    expose:
      - "8080"

  server:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app
    ports:
      - "80:8080"
